services:
  db:
    image: postgres:15
    container_name: piese-auto-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d inventory"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: inventory-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/inventory
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password